### PR TITLE
Added some licensing resources in ch 1

### PR DESCRIPTION
**Pull request by auremoser**
In response to issue #2 , I added a few resources to the licensing section. 

If they are irrelevant or duplicated elsewhere feel free to reject, or clarify on this thread and I'll move them elsewhere and resubmit. I requested a review from the issue author, @tsl-lindsay , but feel free to take it if you're reading this and have merge privileges.

Also, bit of a noob question but are there instructions for running locally in this repo? Do I need to go through the read the docs installs to do that, simple server doesn't render and usually I don't submit PRs without proof that it runs and looks good. 

Really cool guide!

### CODE REVIEW

**Comment by ryanpitts** [comment]
This is awesome @auremoser, thank you! I would say that the "resources on rewarding contributions" items might be a better fit in [this list in Chapter 6](https://github.com/OpenNewsLabs/field-guide-open-source-newsroom/blob/master/docs/Chapter06-Community.md#crediting-contributors) ... do you mind moving them over there?

**Comment by ryanpitts** [comment]
> are there instructions for running locally in this repo?

There aren't! I honestly hadn't really considered that possibility for documentation—I guess I was figuring people would just preview in a markdown editor, or possibly use the [view](https://github.com/auremoser/field-guide-open-source-newsroom/blob/4135f9bf8649e015e84874d2d730bcdd512553ff/docs/Chapter01-Choosing-Open-Source.md) feature on GitHub. But that would be a nice thing to add. Have you seen any documentation-only projects that provide setup instructions that seem useful?

**Comment by auremoser** [comment]
Updated the crediting contributors links to Chapter 6, @ryanpitts !!

I haven't seen good advice about particular read the docs contributors beyond their own installation instructions but something in the readme that defines the ideal process would be cool too, like:

* [Fork the repo](https://help.github.com/articles/fork-a-repo/) to your own Github account
* [Make your changes](https://help.github.com/desktop/guides/contributing/committing-and-reviewing-changes-to-your-project/#3-write-a-commit-message-and-sync-your-changes)
  * (if in the browser) edit the files you'd like to update and save/commit changes
  * (if on the command line) clone your fork of the repository, commit your changes
* [Create a Pull Request](https://help.github.com/articles/creating-a-pull-request/) from your fork to the master branch of the Field Guide to Open Source in the Newsroom repo
* Describe your changes in the Pull Request window and why you made them
  * link to any issues you're responding to in the queue so they can be closed
  * [select a reviewer](https://help.github.com/articles/requesting-a-pull-request-review/) if you'd like, perhaps the person who authored the issue you're responding to.
* Submit your Pull Request, someone will attend to it shortly!
* Well done! You're an open source contributor!

**Comment by ryanpitts** [comment]
Awesome, pulled that thought into [a new issue](https://github.com/OpenNewsLabs/field-guide-open-source-newsroom/issues/59), and will merge these changes. Thanks!

**Pull request merged**
